language: cpp
compiler: gcc

branches:
    only:
        - master

addons:
    # Install lcov for codecoverage
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov
            - libeigen3-dev

before_install:
    # Install SDL2
    - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
    - sudo apt-get update -qq
    - sudo apt-get install libsdl2-dev libsdl2-image-dev -y
    # Install CMake 3.10 and hack $PATH to use it
    - mkdir $HOME/usr
    - export PATH="$HOME/usr/bin:$PATH"
    - wget https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.sh
    - chmod +x cmake-3.10.1-Linux-x86_64.sh
    - ./cmake-3.10.1-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

before_script:
    # Trick to be able to work with graphical applications
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    # symlink the FindEigen3 from package to the repo module folder
    - ln -s /usr/share/cmake-2.8/Modules/FindEigen3.cmake cmake/FindEigen3.cmake
    - sleep 3

script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Coverage
    - make install
    - ctest -V

after_success:
        # Creating report
        - cd ${TRAVIS_BUILD_DIR}
        - lcov --directory . --capture --output-file coverage.info # capture coverage info
        - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
        - lcov --list coverage.info #debug info
        # Uploading report to CodeCov
        - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
