language: cpp
compiler: gcc

branches:
    only:
        - master

before_install:
    # Install CMake 3.10 and hack $PATH to use it
    - mkdir $HOME/usr
    - export PATH="$HOME/usr/bin:$PATH"
    - wget https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.sh
    - chmod +x cmake-3.10.1-Linux-x86_64.sh
    - ./cmake-3.10.1-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3

script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON
    - make
    - ctest -V
